import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:universal_agent_remote/src/json.dart';
import 'package:universal_agent_remote/src/security.dart';

/// Loads a shared vector file from packages/protocol/test_vectors. These files
/// are generated by the Node reference implementation (RFC 8032 test keys) and
/// must byte-match the Dart canonicalizer and verify under DeviceSecurity.
Future<Map<String, Object?>> _readVectorFile(String name) async {
  final file = File('../../packages/protocol/test_vectors/$name');
  final decoded = jsonDecode(await file.readAsString());
  return jsonMap(decoded, name: 'vector file $name');
}

void main() {
  test('canonical JSON shared vectors byte-match Dart canonicalJson', () async {
    final data = await _readVectorFile('canonical_json.json');
    final vectors = jsonList(data['vectors']);
    expect(vectors.length, greaterThanOrEqualTo(5),
        reason: 'vector file must contain shared canonical vectors');
    for (final vector in vectors) {
      final item = jsonMap(vector, name: 'canonical vector');
      expect(canonicalJson(item['input']), requireString(item, 'expected'));
    }
    for (final input in jsonList(data['rejected'])) {
      expect(() => canonicalJson(input), throwsFormatException);
    }
  });

  test('host-signed credential vectors verify on the Dart side', () async {
    final data = await _readVectorFile('credential_vectors.json');
    final hostPublicKeyPem = requireString(data, 'hostPublicKeyPem');
    final security = DeviceSecurity();
    for (final vector in jsonList(data['vectors'])) {
      final item = jsonMap(vector, name: 'credential vector');
      final credential = SignedCredential.fromJson(item);
      final payload =
          await security.verifyCredential(credential, hostPublicKeyPem);
      expect(
          payload, jsonMap(item['expectedPayload'], name: 'expected payload'));
    }
  });

  test('device-signed action vectors verify on the Dart side', () async {
    final data = await _readVectorFile('action_vectors.json');
    final devicePublicKeyPem = requireString(data, 'devicePublicKeyPem');
    final security = DeviceSecurity();
    for (final vector in jsonList(data['vectors'])) {
      final item = jsonMap(vector, name: 'action vector');
      final signed = jsonMap(item['signed'], name: 'signed action');
      final action =
          await security.verifySignedAction(signed, devicePublicKeyPem);
      expect(action, jsonMap(item['expectedAction'], name: 'expected action'));
    }
  });
}
