import type { DesktopBootstrap } from "@shared/desktop_api";
import type { ProviderCapabilities, ProviderConnection } from "../../../../../packages/protocol/src/index";
import type { DesktopSnapshot, Provider, Session, TimelineItem } from "./types";

const now = Date.now();
const ago = (minutes: number): string => new Date(now - minutes * 60_000).toISOString();

export const providers: Provider[] = [
  {
    id: "codex",
    name: "Codex",
    version: "0.147.0",
    state: "online",
    detected: true,
    authenticated: true,
    executable: "codex.exe",
    capabilities: ["List Sessions", "Session History", "Create Session", "Send Message", "Models", "Approvals", "Steering", "Sub-agents", "Interrupt"],
    supportsAttachments: true,
  },
  {
    id: "opencode",
    name: "OpenCode",
    version: "1.2",
    state: "online",
    detected: true,
    authenticated: true,
    executable: "opencode.exe",
    capabilities: ["List Sessions", "Session History", "Create Session", "Send Message", "Models", "Approvals", "Sub-agents", "Interrupt"],
    supportsAttachments: true,
  },
  {
    id: "grok",
    name: "Grok Build",
    version: "1.0",
    state: "online",
    detected: true,
    authenticated: true,
    executable: "grok.exe",
    capabilities: ["List Sessions", "Session History", "Create Session", "Send Message", "Models", "ACP", "Interrupt"],
    supportsAttachments: false,
  },
  {
    id: "direct",
    name: "Direct API",
    version: "1.0",
    state: "online",
    detected: true,
    authenticated: false,
    capabilities: ["List Sessions", "Session History", "Create Session", "Send Message", "Models", "Attachments"],
    supportsAttachments: true,
  },
  {
    id: "tethoq-example",
    name: "Tethoq Example Connector",
    version: "2.4.1",
    state: "online",
    detected: true,
    authenticated: true,
    capabilities: ["List Sessions", "Session History", "Create Session", "Send Message", "Models", "Steering", "Attachments", "Message Queue"],
    supportsAttachments: true,
  },
];

function protocolCapabilities(overrides: Partial<ProviderCapabilities> = {}): ProviderCapabilities {
  return {
    authentication: false,
    listSessions: true,
    paginatedSessions: false,
    sessionHistory: true,
    createSession: true,
    resumeSession: true,
    sendMessage: true,
    steering: false,
    streamingText: true,
    toolEvents: true,
    commandEvents: true,
    fileChanges: true,
    approvals: true,
    userInput: true,
    interrupt: true,
    modelEnumeration: true,
    projectAssociation: true,
    sessionRelationships: true,
    messageEditing: false,
    remoteConnectivity: "local",
    notes: [],
    ...overrides,
  };
}

function demoConnection(provider: Provider, overrides: Partial<ProviderCapabilities> = {}): ProviderConnection {
  return {
    providerId: provider.id,
    displayName: provider.name,
    state: provider.state === "online" ? "online" : "offline",
    detected: provider.detected,
    authenticated: provider.authenticated,
    capabilities: protocolCapabilities(overrides),
    ...(provider.version ? { nativeVersion: provider.version } : {}),
  };
}

export const demoBootstrap: DesktopBootstrap = {
  app: { name: "Tethoq", version: "0.1.0-preview", platform: "win32", packaged: false },
  host: {
    id: "desktop-preview",
    displayName: "This computer",
    platform: "windows",
    connectionState: "online",
    protocolVersion: 1,
    lastSeenAt: new Date(now).toISOString(),
    relayConnected: false,
  },
  providers: providers.map((provider) => demoConnection(provider, provider.id === "tethoq-example" ? { steering: true } : {})),
  allowedProviders: providers.map((provider) => provider.id),
  connectors: {
    directory: "C:\\Tethoq\\connectors",
    loaded: [{
      id: "tethoq-example",
      name: "Tethoq Example Connector",
      version: "2.4.1",
      source: "external",
      fingerprint: `sha256:${"1".repeat(64)}`,
      directory: "C:\\Tethoq\\connectors\\tethoq-example",
      permissions: { filesystem: "workspace", network: false, spawnProcesses: true },
      capabilities: { attachments: true, reasoningEfforts: true, messageQueue: true },
    }],
    pending: [{
      id: "community.sample",
      name: "Community Sample Connector",
      version: "1.0.0",
      fingerprint: `sha256:${"2".repeat(64)}`,
      directory: "C:\\Tethoq\\connectors\\community-sample",
      runtime: { command: "node", args: ["./connector.js"], cwd: "C:\\Tethoq\\connectors\\community-sample" },
      requestedEnvironmentNames: ["SAMPLE_API_KEY"],
      permissions: { filesystem: "workspace", network: true, spawnProcesses: false },
    }],
    diagnostics: [{
      directory: "C:\\Tethoq\\connectors\\invalid-sample",
      state: "rejected",
      connectorId: "invalid-sample",
      message: "Manifest rejected: the connector entrypoint must stay inside its own folder.",
    }],
  },
  latestSequence: 0,
  openCode: { state: "managed", url: "http://127.0.0.1:4096/", managed: true, message: "Managed local provider runtime" },
};

export const sessions: Session[] = [
  {
    id: "desktop-harness",
    providerId: "codex",
    title: "Build the Tethoq desktop app",
    state: "working",
    project: "Tethoq",
    workingDirectory: "C:\\Projects\\sample-app",
    preview: "Building a polished desktop workspace and connecting provider-native controls.",
    updatedAt: ago(1),
    model: "GPT-5.6 Sol",
    effort: "Ultra",
    unread: 2,
    childCount: 2,
  },
  {
    id: "auth-regression",
    providerId: "opencode",
    title: "Fix authentication regression",
    state: "needs_approval",
    project: "Account service",
    workingDirectory: "C:\\Projects\\account-service",
    preview: "The focused fix is ready. Permission is needed to run the migration.",
    updatedAt: ago(11),
    model: "OpenCode default",
    effort: "High",
    unread: 1,
  },
  {
    id: "onboarding",
    providerId: "codex",
    title: "Refine onboarding flow",
    state: "needs_input",
    project: "Desktop app",
    workingDirectory: "C:\\Projects\\desktop-app",
    preview: "Waiting for a decision on the first-run layout.",
    updatedAt: ago(28),
    model: "GPT-5.6 Terra",
    effort: "High",
  },
  {
    id: "cache",
    providerId: "grok",
    title: "Repair cache invalidation",
    state: "completed",
    project: "API service",
    workingDirectory: "C:\\Projects\\api-service",
    preview: "Fixed stale cache entries after background updates.",
    updatedAt: ago(52),
    model: "Grok Code",
    effort: "Default",
  },
  {
    id: "checkout",
    providerId: "opencode",
    title: "Add checkout end-to-end test",
    state: "idle",
    project: "Storefront",
    workingDirectory: "C:\\Projects\\storefront",
    preview: "Browser flow is drafted and paused before checkout.",
    updatedAt: ago(135),
    model: "OpenCode default",
    effort: "Default",
  },
  {
    id: "release",
    providerId: "grok",
    title: "Investigate deployment failure",
    state: "failed",
    project: "Platform",
    workingDirectory: "C:\\Projects\\platform",
    preview: "Build stopped because a Windows SDK component is missing.",
    updatedAt: ago(310),
    model: "Grok Code",
    effort: "Default",
  },
];

const desktopTimeline: TimelineItem[] = [
  {
    id: "u1",
    kind: "user",
    body: "Add bulk-edit controls to the inventory dashboard and keep the existing keyboard workflow.",
    images: [{ name: "reference.png", mimeType: "image/png", dataUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=" }],
    timestamp: ago(24),
  },
  {
    id: "r1",
    kind: "reasoning",
    title: "Mapped the existing interface",
    body: "The current dashboard patterns are consistent. I am extending its filters, table controls, and validation states without changing navigation.",
    timestamp: ago(20),
    state: "completed",
  },
  {
    id: "t1",
    kind: "tool",
    title: "Inspected application UI",
    body: "Reviewed the dashboard components, navigation, and existing table behavior.",
    detail: "18 files read",
    timestamp: ago(18),
    state: "completed",
  },
  {
    id: "c1",
    kind: "command",
    title: "Typecheck renderer",
    body: "npm run typecheck",
    detail: "Running in C:\\Projects\\sample-app",
    timestamp: ago(6),
    state: "running",
  },
  {
    id: "f1",
    kind: "file",
    title: "Created desktop renderer",
    body: "src/renderer/src/App.tsx\nsrc/renderer/src/styles.css",
    detail: "+1,284 lines",
    timestamp: ago(4),
    state: "completed",
  },
  {
    id: "s1",
    kind: "subagent",
    title: "Provider integration",
    body: "A delegated worker is wiring the local Codex, OpenCode, and Grok adapters into the desktop bridge.",
    detail: "Backend engineer · working",
    timestamp: ago(3),
    state: "running",
  },
  {
    id: "a1",
    kind: "assistant",
    body: "The desktop shell is taking shape: persistent coding-tool navigation on the left, a searchable task inbox in the middle, and the live coding workspace on the right. Provider controls remain capability-driven.",
    timestamp: ago(1),
    state: "running",
  },
];

export const demoSnapshot: DesktopSnapshot = {
  connected: true,
  hostName: "This computer",
  providers,
  sessions,
  timelines: {
    "desktop-harness": desktopTimeline,
    "auth-regression": [
      {
        id: "auth-user",
        kind: "user",
        body: "Fix the authentication regression and verify the migration.",
        timestamp: ago(39),
      },
      {
        id: "auth-assistant",
        kind: "assistant",
        body: "The token refresh path is fixed and its regression test passes. The database migration needs your approval before I can finish verification.",
        timestamp: ago(12),
      },
    ],
    onboarding: [
      {
        id: "onboarding-user",
        kind: "user",
        body: "Make the onboarding much cleaner.",
        timestamp: ago(60),
      },
      {
        id: "onboarding-assistant",
        kind: "assistant",
        body: "I have two strong directions ready. Choose the emphasis and I will finish the flow.",
        timestamp: ago(29),
      },
    ],
    cache: [],
    checkout: [],
    release: [
      {
        id: "release-error",
        kind: "error",
        title: "Build stopped",
        body: "Windows SDK 10.0.26100 was not found. Install the component or select an available SDK.",
        timestamp: ago(310),
        state: "failed",
      },
    ],
  },
  approvals: [
    {
      id: "approval-migration",
      sessionId: "auth-regression",
      title: "Run the account migration?",
      reason: "This updates the refresh-token index used by the repaired authentication path.",
      command: "npm run db:migrate",
      directory: "C:\\Projects\\account-service",
      files: ["migrations/20260813_refresh_token_index.sql"],
      choices: [
        { id: "approve", label: "Run migration", kind: "approve" },
        { id: "reject", label: "Not now", kind: "reject" },
      ],
    },
  ],
  inputRequests: [
    {
      id: "input-onboarding",
      sessionId: "onboarding",
      title: "Choose the onboarding emphasis",
      prompt: "Should the first screen lead with local privacy or speed of setup?",
      answerKey: "emphasis",
      options: ["Local privacy", "Fast setup"],
    },
  ],
  models: {
    codex: [
      { id: "gpt-5.6-sol", name: "GPT-5.6 Sol", efforts: ["Low", "Medium", "High", "Ultra"] },
      { id: "gpt-5.6-terra", name: "GPT-5.6 Terra", efforts: ["Low", "Medium", "High", "Ultra"] },
    ],
    opencode: [{ id: "opencode-default", name: "OpenCode default", efforts: ["Default", "High"] }],
    grok: [{ id: "grok-code", name: "Grok Code", efforts: ["Default"] }],
    direct: [
      { id: "openai::gpt-5.6-sol", name: "GPT-5.6 Sol", efforts: ["Low", "Medium", "High"], inputModalities: ["text", "image"], endpointId: "openai", endpointName: "OpenAI API", source: "Direct API", walletKind: "user_api", apiKeyConfigured: false, caution: "Add an OpenAI API key before use." },
      { id: "vercel::zai/glm-5.2", name: "GLM-5.2 via Vercel", efforts: ["Default"], endpointId: "vercel", endpointName: "Vercel AI Gateway", source: "Direct API", walletKind: "user_api", apiKeyConfigured: false },
    ],
    "tethoq-example": [
      { id: "tethoq-example-reasoning", name: "Tethoq Example Reasoning", efforts: ["Balanced", "Deep"] },
      { id: "tethoq-example-fast", name: "Tethoq Example Fast", efforts: ["Fast"] },
    ],
  },
};
